"""initial schema -- all octflux tables

Baseline migration: creates the whole schema from the single SQLAlchemy
``MetaData`` so it stays dialect-agnostic. Subsequent changes use autogenerated
revisions diffed against that metadata.

Revision ID: 0001
Revises:
"""
from __future__ import annotations

from alembic import op

from octflux.schema.tables import metadata
from octflux.schema.timescale import create_hypertables

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    metadata.create_all(bind)
    create_hypertables(bind)  # no-op unless Postgres + TimescaleDB


def downgrade() -> None:
    metadata.drop_all(op.get_bind())
